services:

  postgres:
    image: postgres:16-bullseye
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGTZ: UTC   # ← timezone del servidor postgres
      TZ: UTC     # ← timezone del contenedor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c timezone=UTC
      -c log_timezone=UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      

  redis:
    image: redis:7-alpine
    container_name: marketplace-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # ← activa la persistencia para que si el contenedor se reinicia no pierdas el cache.
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: marketplace-rabbitmq
    ports:
      - "5672:5672"     # ← puerto para la conexión AMQP
      - "15672:15672"   # ← puerto para el panel de administración web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10


  localstack:
    image: localstack/localstack:4.6.0
    container_name: marketplace-localstack
    ports:
      - "4566:4566" # ← puerto único para todos los servicios de AWS simulados
    environment:
      - SERVICES=sqs # ← le dice a LocalStack que solo levante el servicio de SQS
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10


  vault:
    image: hashicorp/vault:1.20.3
    container_name: marketplace-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot  # ← arranca Vault en modo desarrollo con un token fijo myroot. En producción nunca usarías esto, pero para desarrollo local es perfecto porque no necesitás inicializar ni unseal Vault manualmente.
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      DB_HOST: postgres
      REDIS_HOST: redis
      RABBIT_HOST: rabbitmq
      SQS_ENDPOINT: http://localstack:4566
      EXCHANGE_RATE_API_KEY: 848e46f7b20b6bdf9d887b8a  # ← key real
    cap_add:
      - IPC_LOCK  # ←  es necesario para que Vault pueda bloquear memoria y evitar que los secretos se escriban en el swap del sistema operativo.
    volumes:
      - vault_data:/vault/data
      - ./vault-init.sh:/vault/init/vault-init.sh
    entrypoint: >
      sh -c "vault server -dev &
             sh /vault/init/vault-init.sh &&
             wait"
    healthcheck:
      test: [ "CMD-SHELL", "VAULT_ADDR=http://127.0.0.1:8200 vault status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10


  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: marketplace-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    depends_on:
      marketplace-api:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --tries=1 http://localhost:9090/-/healthy -O /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5


  grafana:
    image: grafana/grafana:12.1.1
    container_name: marketplace-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:3000/api/health -O /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5


  marketplace-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_VAULT_URI: http://vault:8200  # ← solo existe cuando se corre el docker-compose
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      localstack:
        condition: service_healthy
      vault:
        condition: service_healthy


  notification-service:
      build:
        context: ../notification-service
        dockerfile: Dockerfile
      container_name: marketplace-notification
      ports:
        - "8081:8081"
      environment:
        SPRING_PROFILES_ACTIVE: docker
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: 5672
        SPRING_RABBITMQ_USERNAME: admin
        SPRING_RABBITMQ_PASSWORD: admin
      depends_on:
        rabbitmq:
          condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  localstack_data:
  vault_data:
  prometheus_data:
  grafana_data: