version: '3.8'

services:
  postgres:
    image: postgres:16-bullseye
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGTZ: UTC   # ← timezone del servidor postgres
      TZ: UTC     # ← timezone del contenedor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c timezone=UTC
      -c log_timezone=UTC

  redis:
    image: redis:7-alpine
    container_name: marketplace-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # ← activa la persistencia para que si el contenedor se reinicia no pierdas el cache.

volumes:
  postgres_data:
  redis_data: