sonar.projectKey=tincho77777_marketplace
sonar.organization=tincho77777

sonar.projectName=marketplace
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

sonar.exclusions=**/configuration/**,**/*Application.java,**/entity/**,**/swagger/**,**/request/**,**/response/**,**/exceptions/**

sonar.coverage.exclusions=**/configuration/**,**/*Application.java,**/entity/**,**/swagger/**,**/request/**,**/response/**,**/exceptions/**

sonar.sourceEncoding=UTF-8