spring.application.name=marketplace

# =========================
# DATASOURCE - H2
# =========================
#spring.datasource.url=jdbc:h2:mem:marketplace
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.defer-datasource-initialization=true

# =========================
# DATASOURCE - POSTGRES
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# =========================
# REDIS
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# =========================
# CACHE
# =========================
spring.cache.type=redis
# El TTL se configura directamente en el bean RedisCacheManager (RedisConfig.java ? entryTtl)
# La propiedad spring.cache.redis.time-to-live no tiene efecto cuando se define un bean RedisCacheManager propio

# =========================
# RABBITMQ
# =========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

# fuerza la conexion al arrancar la api, colocar en false una vez probado
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.template.mandatory=true

# nombres de exchange, queue y routing key como propiedades
rabbitmq.exchange=marketplace.exchange
rabbitmq.queue=product.created.queue
rabbitmq.routing-key=product.created
