# =========================
# VAULT (Docker)
# =========================
spring.cloud.vault.uri=http://vault:8200

# =========================
# DATASOURCE (Docker)
# =========================
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# =========================
# CACHE
# =========================
spring.cache.type=redis

# =========================
# RABBITMQ
# =========================
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.template.mandatory=true
rabbitmq.exchange=marketplace.exchange
rabbitmq.queue=product.created.queue
rabbitmq.routing-key=product.created

# =========================
# RESILIENCE4J
# =========================
resilience4j.circuitbreaker.instances.rabbitmq.sliding-window-size=10
resilience4j.circuitbreaker.instances.rabbitmq.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.rabbitmq.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.rabbitmq.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.rabbitmq.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.retry.instances.rabbitmq.max-attempts=3
resilience4j.retry.instances.rabbitmq.wait-duration=1s
resilience4j.retry.instances.rabbitmq.enable-exponential-backoff=true
resilience4j.retry.instances.rabbitmq.exponential-backoff-multiplier=2
resilience4j.circuitbreaker.instances.sqs.sliding-window-size=10
resilience4j.circuitbreaker.instances.sqs.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.sqs.wait-duration-in-open-state=30s
resilience4j.retry.instances.sqs.max-attempts=3
resilience4j.retry.instances.sqs.wait-duration=1s
resilience4j.circuitbreaker.instances.exchangeRate.sliding-window-size=5
resilience4j.circuitbreaker.instances.exchangeRate.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.exchangeRate.wait-duration-in-open-state=60s
resilience4j.retry.instances.exchangeRate.max-attempts=2
resilience4j.retry.instances.exchangeRate.wait-duration=2s

# actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers,retries
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=marketplace-api
management.metrics.tags.environment=docker
management.health.circuitbreakers.enabled=true
management.health.redis.enabled=true
management.health.rabbit.enabled=true
management.health.db.enabled=true


management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0
